version: "3.9"

services: 
  maintenance:
    image: nginx:mainline-alpine
    container_name: nginx-maint
    ports:
      - "80:80"
      #Enable for HTTPS
#      - "443:443"
    volumes:
      - ./isdown/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./isdown/html:/usr/share/nginx/html
      - ./isdown/logs:/var/www/logs
      - ./nginx/conf_other/onlych.conf:/etc/nginx/conf.d/onlych.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/data-maint:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment: 
      - NGINX_DOM=${MY_DOMAIN}
      - NGINX_WWWDOM=${MY_WWW_DOMAIN}
      - CERT_PATH=${SSL_CERT_PATH}
      - CERTKEY_PATH=${SSL_CERTKEY_PATH}
      - CH_ONLY=${CH_ONLY}
    command: /bin/sh -c "envsubst '$$NGINX_DOM $$NGINX_WWWDOM $$CERT_PATH $$CERTKEY_PATH $$CH_ONLY' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/data-maint:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on: 
      - maintenance
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERT_EMAIL} --agree-tos --no-eff-email --staging -d ${MY_DOMAIN}  -d ${MY_WWW_DOMAIN}

volumes:
  certbot-var: